services:

  db:
    image: postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_BASE_URL: ${APP_BASE_URL}
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_BASE_URL: ${APP_BASE_URL}
    ports:
      - "8080:8080"